#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 11 14:22:08 2018

@author: jc96
"""

import json
import csv

with open('conflict_data.json') as file:
    datafull = json.load(file)

#first testing on the sample
for item in datafull:
    item.pop('id')
    item.pop('code_status')
    item.pop('dyad_dset_id')
    item.pop('dyad_new_id')
    item.pop('side_a_dset_id')
    item.pop('side_a_new_id')
    item.pop('side_b_dset_id')
    item.pop('side_b_new_id')
    item.pop('source_date')
    item.pop('source_original')
    item.pop('where_description')
    item.pop('adm_2')
    item.pop('adm_1')
    item.pop('geom_wkt')
    item.pop('priogrid_gid')
    item.pop('country_id')
    item.pop('region')
    item.pop('event_clarity')
    item.pop('date_prec')
    
with open('preproc.csv', 'w', newline='') as file:
    csvwriter = csv.writer(file, delimiter=',', quotechar='"', quoting=csv.QUOTE_NONNUMERIC)
    csvwriter.writerow(['relid', 'year', 'active_year', 'type_of_violence', 'conflict_dset_id', 'conflict_new_id', 'conflict_name', 'dyad_name', 'side_a', 'side_b', 'number_of_sources', 'source_article', 'source_office', 'source_headline', 'where_prec', 'where_coordinates', 'latitude', 'longitude', 'country', 'date_start', 'date_end', 'deaths_a', 'deaths_b', 'deaths_civilians', 'deaths_unknown', 'best', 'high', 'low'])  
    for item in range(len(datafull)):
        csvwriter.writerow(datafull[item].values())
